### ISSUE TITLE
/Server Add a /GetBusinesses route to the /Human folder

### ISSUE THREAD

**Issue by zenmanenergy** [zenmanenergy/SoldDownTheRiver#27]
Add a /GetBusinesses route to the /Humans folder.

It should work exactly like the /GetBusinesses route in the /Businesses folder. Look at that and copy the functionality.

**Comment by JohnPark24** [comment]
Hi could I work on this?

**Comment by zenmanenergy** [comment]
JohnPark-

At the moment this is a high school project. While I would love your help I am using this project as a way to teach high school students how to write html, js, svelte, css, python and sql. I suspect most of the code would be very simple for you.
